individual_stats = ["AttackTimes", "DefendTimes", "Rounds"]
team_stats = {"AttackTimes", "DefendTimes", "Rounds"}
mapping_dic = {"InterceptionsPerDefense": "interceptionAll",
               "InterceptionsPerD90m": "interceptionAll",
               "InterceptionsTotal": "interceptionAll",
               "TacklesPerDefense": "tackleWon",
               "TacklesPerD90m": "tackleWon",
               "TacklesTotal": "tackleWon",
               "AerialWonPerDefense": "duelAerialWon",
               "AerialWonPerD90m": "duelAerialWon",
               "AerialWonTotal": "duelAerialWon",
               "AerialLossPerDefense": "duelAerialLost",
               "AerialLossPerD90m": "duelAerialLost",
               "AerialLossTotal": "duelAerialLost",
               "SavePerDefense": "keeperSaveTotal",
               "SavePerD90m": "keeperSaveTotal",
               "SaveTotal": "keeperSaveTotal",
               "FoulPerDefense": "foulCommitted",
               "FoulPerD90m": "foulCommitted",
               "FoulTotal": "foulCommitted",
               "FouledPerAttack": "foulGiven",
               "FouledPerA90m": "foulGiven",
               "FouledTotal": "foulGiven",
               "SuccessPassPerAttack": "passAccurate",
               "SuccessPassPerA90m": "passAccurate",
               "SuccessPassTotal": "passAccurate",
               "UnSuccessPassPerAttack": "passInaccurate",
               "UnSuccessPassPerA90m": "passInaccurate",
               "UnSuccessPassTotal": "passInaccurate",
               "PassPerAttack": "totalPass",
               "PassPerA90m": "totalPass",
               "PassTotal": "totalPass",
               "ClearPerDefense": "clearanceTotal",
               "ClearPerD90m": "clearanceTotal",
               "ClearTotal": "clearanceTotal",
               "ShotPerAttack": "shotsTotal",
               "ShotPerA90m": "shotsTotal",
               "ShotTotal": "shotsTotal",
               "GoalPerAttack": "goalNormal",
               "GoalPerA90m": "goalNormal",
               "GoalTotal": "goalNormal",
               "ForwardPassPerAttack": "passForward",
               "ForwardPassPerA90m": "passForward",
               "ForwardPassTotal": "passForward",
               "ForwardPassMeterPerAttack": "forwardPassMeter",
               "ForwardPassMeterPerA90m": "forwardPassMeter",
               "ForwardPassMeterTotal": "forwardPassMeter",
               "DribblePerAttack": "dribbleWon",
               "DribblePerA90m": "dribbleWon",
               "DribbleTotal": "dribbleWon",
               "PassCrossAccuratePerAttack": "passCrossAccurate",
               "PassCrossAccuratePerA90m": "passCrossAccurate",
               "PassCrossAccurateTotal": "passCrossAccurate",
               "DispossessedPerAttack": "dispossessed",
               "DispossessedPerA90m": "dispossessed",
               "DispossessedTotal": "dispossessed",
               "DispossessedInD3rdPerAttack": "dispossessedInD3rd",
               "DispossessedInD3rdPerA90m": "dispossessedInD3rd",
               "DispossessedInD3rdTotal": "dispossessedInD3rd",
               "KeyPassPerAttack": "keyPass",
               "KeyPassPerA90m": "keyPass",
               "KeyPassTotal": "keyPass",
               "PassLeadingKpPerAttack": "passLeadingKp",
               "PassLeadingKpPerA90m": "passLeadingKp",
               "PassLeadingKpTotal": "passLeadingKp",
               "SuccessfulPassToA3rdPerAttack": "successfulPassToA3rd",
               "SuccessfulPassToA3rdPerA90m": "successfulPassToA3rd",
               "SuccessfulPassToA3rdTotal": "successfulPassToA3rd",
               "TurnoverPerAttack": "turnover",
               "TurnoverPerA90m": "turnover",
               "TurnoverTotal": "turnover",
               }
STATS_KEYS = [u'id', u'team', u'name', u'position', u'playMins', u'result', u'goals', u'assists', u'goalsConceded',
              u'penaltyConceded',
              u'cornersTotal', u'aerialsWon', u'dribblesLost', u'shotsTotal', u'passesAccurate', u'tackleUnsuccesful',
              u'defensiveAerials', u'aerialsTotal', u'offensiveAerials', u'passesTotal', u'throwInsTotal',
              u'offsidesCaught', u'interceptions', u'ratings', u'touches', u'dispossessed', u'parriedSafe',
              u'claimsHigh',
              u'clearances', u'throwInAccuracy', u'collected', u'parriedDanger', u'possession', u'shotsOffTarget',
              u'dribblesAttempted',
              u'shotsOnPost', u'dribblesWon', u'cornersAccurate', u'tackleSuccess', u'throwInsAccurate',
              u'dribbleSuccess', u'errorsCount',
              u'aerialSuccess', u'shotsBlocked', u'tacklesTotal', u'tackleSuccessful', u'shotsOnTarget',
              u'dribbledPast',
              u'passesKey', u'foulsCommited', u'totalSaves', u'passSuccess', u'claimsTotal', u'claimsGround']

RATING_KEYS = ['id', 'team', 'name', 'position', 'xtPosition', 'adjustedRating', 'overallRating', 'parriedDangerRating',
               'cccPassesRating', 'shotsAccuracyRating',
               'errorsRating', 'goalsConcededRating', 'dribbleSuccessRating', 'aerialSuccessRating', 'collectedRating',
               'totalSavesRating', 'dribbledPastRating', 'goalsRating', 'defenseThreeRatting', 'passesAccuracyRating']